name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t danshinde/iolgendr-api:latest -t danshinde/iolgendr-api:${{ github.ref_name }} .

    # Step 4: Push the Docker image
    - name: Push Docker image
      run: |
        docker push danshinde/iolgendr-api:latest
        docker push danshinde/iolgendr-api:${{ github.ref_name }}

      # Step 5: Log in to Docker Hub (Second Account: Armstrong)
    - name: Log in to Docker Hub (Armstrong)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_ARMSTRONG }}
        password: ${{ secrets.DOCKER_PASSWORD_ARMSTRONG }}

    # Step 6: Retag the Docker image for Second Account (Armstrong)
    - name: Tag Docker image for Second Account
      run: |
        docker tag danshinde/iolgendr-api:latest pravinshinde01/iolgendr-api:latest
        docker tag danshinde/iolgendr-api:${{ github.ref_name }} pravinshinde01/iolgendr-api:${{ github.ref_name }}

    # Step 7: Push Docker image to Second Account (Armstrong)
    - name: Push Docker image to Second Account
      run: |
        docker push pravinshinde01/iolgendr-api:latest
        docker push pravinshinde01/iolgendr-api:${{ github.ref_name }}